### ISSUE TITLE
Account activation breaks automation of demo/accounts.py

### ISSUE THREAD

**Issue by benoitbryon** [novapost/pydocusign#41]
At the moment, as of pydocusign version 0.10, demo/accounts.py creates an user account then deletes it.

As seen in Travis-CI.org, it used to work: see https://travis-ci.org/novapost/pydocusign/jobs/42855139#L244-L256

But now it is broken: see https://travis-ci.org/novapost/pydocusign/jobs/46837725#L287-L306
Looks like the created user account now requires activation. This step has not been automated yet.

**Find a solution to pass the tests!**

Here are some options:

* automate account activation. Implies fetching and parsing email, then performing HTTP requests. Quite complicated and greedy, but should be possible.
* create account using options so that activation is not necessary. If such options are available, should be the simplest option.
* other ideas? Feel free to propose fixes in comments below ;)

Note: as pydocusign's maintainer I'd like to avoid mocking DocuSign, because I like the idea of having integration tests. This ticket is a typical example where integration reveals issues.

**Comment by benoitbryon** [comment]
Closed via #42

**Comment by bersace** [comment]
I suggest to reopen and wait for the second PR that actually fix this to close the issue.
